### PR TITLE
Fix latitude and longitude doubles to accurately reflect west and south values

### PR DESCRIPTION
**Pull request by ghost**
The code was commented out, but forced the all positive coordinates into all negative - this fix makes latitude and longitude correct.

### CODE REVIEW

**Comment by copercini** [comment]
Nice PR, but it's missing the parse part and variables declaration

**Comment by ghost** [comment]
Not sure I understand - this repo already has/had everything, to the point I was just uncommenting the existing code and fixing the subtraction to addition in two cases to be correct.

For reference, the parsing is at [MC20_GNSS.cpp@282](https://github.com/Seeed-Studio/Seeed_Wio_GPS_Board/blob/master/MC20_GNSS.cpp#L282) and the variables I think you refer to are in [MC20_GNSS.h@54](https://github.com/Seeed-Studio/Seeed_Wio_GPS_Board/blob/master/MC20_GNSS.h#L54)

**Comment by copercini** [comment]
Oh, I'm running an old version which does not have these things...

Thanks to point me out!

**Comment by ghost** [comment]
Aha, that explains it. Glad to!

**Pull request merged**
